### ISSUE TITLE
Migrate to 3.0

### ISSUE THREAD

**Issue by nouira** [Azure/dotnet-template-azure-iot-edge-function#51]
Is there any plan to migrate to 3.0 ?

The images are available https://github.com/Azure/azure-functions-docker

**Comment by konichi3** [comment]
Hi

@nouira 
We do not have any plans to support .NET SDK v3 at this time. This issue is in our backlog now and we will circle back when we have an update.

Meanwhile, is this blocking you? v3 supports more language such as python, Java, and Node. Are there any language you use to build Azure function for IoT Edge?

**Comment by marianan** [comment]
Azure functions module template has been updated to support .Net core 3.1
